### ISSUE TITLE
Suggestion: CPU affinity and async queue

### ISSUE THREAD

**Issue by JCKodel** [nxtSwitch/isolate_supervisor#2]
I'm brainstorming a state management without state (it will respond reactively for messages sent to an Stream (a event bus), so, for example, when a database record is saved, a message saying that entity has changed is published then the StreamBuilder filters those messages to update all parts that should react to a change in that table).

While doing this, I've noticed that "state" is CPU dependent. For instance:

```dart
var _currentCount = 0;

Future<NewCountMessage> delayedIncrement(IsolateContext context) async {
  await Future.delayed(const Duration(seconds: 1));

  _currentCount++;

  return NewCountMessage(_currentCount);
}

Future<void> setInitialValue(IsolateContext context) async {
  _currentCount = context.arguments.nearest();

  return NewCountMessage(_currentCount);
}
```

This code runs fine when using only 1 CPU (because there will be only one isolate and `_currentCount` will be bound to it).
While running on multiple CPU's, isolate_supervior queue those methods in different "threads". That's nice, that's what we want to ensure we can use all CPU's, but, for this particular piece of code, I *must* use always the same supervisor (otherwise there will be a lot of copies of `_currentCount`).

This is what I'm doing to implement affinity:

```dart
import 'package:isolate_supervisor/isolate_supervisor.dart';

typedef IsolateFuture<T> = Future<T> Function(IsolateContext);
typedef IsolateStream<T> = Stream<T> Function(IsolateContext);

class Thread {
  static final instance = Thread._();
  Thread._();

  final _supervisors = List<IsolateSupervisor>.generate(
    IsolateSupervisor.availableProcessors,
    (index) => IsolateSupervisor.spawn(count: 1, lazily: false),
  );

  Future<T> run<T>(int cpu, IsolateFuture<T> isolateFuture, [List<dynamic> params]) {
    return _supervisors[cpu % _supervisors.length].compute(isolateFuture, params);
  }

  void start<T>(int cpu, IsolateFuture<T> isolateFuture, [List<dynamic> params]) {
    _supervisors[cpu % _supervisors.length].compute(isolateFuture, params);
  }

  Stream<T> stream<T>(int cpu, IsolateStream<T> isolateStream, [List<dynamic> params]) {
    return _supervisors[cpu % _supervisors.length].launch(isolateStream, params);
  }
}
```

The idea here is to have one cpu slot (even if it doesn't exist) to each background work I can do (for example, 0 for database (where SQFLite database is global in its supervisor, 1 for web calls (where HttpClient is global to its supervisor) and 2 for some generic work (such as image manipulation, etc.).

Also, would be lovely if the supervisor could work with a stream that is executed in a isolate.

For example:

```dart
import 'dart:async';

import 'thread.dart';

class Mediator {
  static final instance = Mediator._();
  Mediator._();

  final _streamController = StreamController.broadcast();

  Stream get messageStream => _streamController.stream;

  void publish(dynamic message) {
    _streamController.add(message);
  }

  void isolate<T>(IsolateFuture<T> isolateFuture, [List<dynamic> params]) {
    Thread.instance
        .run(0, isolateFuture, params)
        .then((response) => _streamController.add(response))
        .catchError((error) => _streamController.addError(error));
  }
}
```

That code allows me to send messages without need to await them, then they are processed somewhere else (notice the last function: it is processed in an isolate that returns the response message so I can broadcast it).

This allows me to do things like this:

```dart
import 'package:flutter/material.dart';
import 'package:isolate_supervisor/isolate_supervisor.dart';

import 'kfx/mediator.dart';

@immutable
class NewCountMessage {
  final int count;

  const NewCountMessage(this.count);
}

var _currentCount = 0;

Future<NewCountMessage> delayedIncrement(IsolateContext context) async {
  await Future.delayed(const Duration(seconds: 1));

  _currentCount++;

  return NewCountMessage(_currentCount);
}

Future<void> setInitialValue(IsolateContext context) async {
  _currentCount = context.arguments.nearest();

  return NewCountMessage(_currentCount);
}

Future<void> main() async {
  Mediator.instance.isolate(setInitialValue, [15]);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  void _incrementCounter() {
    Mediator.instance.isolate(delayedIncrement);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            StreamBuilder<NewCountMessage>(
              stream: Mediator.instance.messageStream.where((e) => e is NewCountMessage).cast<NewCountMessage>(),
              builder: (context, snapshot) {
                final style = Theme.of(context).textTheme.headline4;

                if (snapshot.hasData == false) {
                  return Text("0", style: style);
                }

                if (snapshot.hasError) {
                  return Text(snapshot.error.toString(), style: style);
                }

                return Text(snapshot.data.count.toString(), style: style);
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

The idea here is to be able to call a database load method without having to await it, execute it on an isolate and them broadcast the results for whatever number of StreamBuilders interested in that particular message (I can filter the stream even for the Id of the table, so it will update itself only if it displaying the record with id = x). 

I'm still thinking how I would do dependencies (for example: an insert in the table X should broadcast a message Y so all StreamBuilders showing data from that table are updated). I can't manipulate the event bus in the isolate (because it would be a copy of it)

BTW, what is the purpose of `IsolateContext.sink`? Can I use it to comunicate with the main thread? If so, how I do that?

---

Another related suggestion:

In the above sample, the counter is delayed 1 second (emulating some slow web call, for example). If you hit the button 3 times, all increments are called in a sequence (so the entire code will run in 3 seconds).

It would be awesome if we could create parallel tasks (those 3 buttons click would still run on an isolate, but it would run in parallel on the event loop, like the main thread would do).

**Comment by nxtSwitch** [comment]
Hi @JCKodel 👋
Thanks for opening an issue!

Theoretically it is possible to implement parallel tasks in isolate, but it may lead to some rescrictions: for example, it will become impossible to cancel a one specific task (because as far as I know, there isn't a way to cancel a Future).

Further implementation needs to be considered.

---

Yes, `IsolateContext.sink` is added for more agile interaction with the main thread, mostly while working with tasks by the `IsolateSupervisor.execute` method.

Also, by using the `IsolateContext.compute` method, you can return the value in advance by `sink` methods. This action will complete the execution of `compute` with the returned value. And the task in the isolate will remain active and will be able to perform additional operations, like closing connection with the database.

---

The idea to CPU affinity is interesting, I will try to implement this feature in the next version.
I am thinking maybe we can have something like `IsolateSupervisor[0].compute`. Perhaps you have any suggestions on how to do this more conveniently?

---

You can just use `IsolateSupervisor.execute` within your `Mediator` class. Kind of:

```dart
class Thread {
  IsolateTask<T> run<T>(int cpu, IsolateFuture<T> isolateFuture, [List<dynamic> params]) {
    return _supervisors[cpu % _supervisors.length].execute(isolateFuture, params);
  }
}

class Mediator {
  final _streamController = StreamController.broadcast();

  void isolate<T>(IsolateFuture<T> isolateFuture, [List<dynamic> params]) {
    final task = Thread.instance.run(0, isolateFuture, params);
    _streamController.addStream(task.output);
  }
}
```

Hope that helps 👍

P.S. Im completing central registry for values that can be used across isolates now, I can’t estimate deadlines yet.
